### ISSUE TITLE
Format of Date UTC error

### ISSUE THREAD

**Issue by bellsenawat** [phng/angular-input-time#5]
This lib very helpful for me, but I faced the problem that by default this lib is work fine for new Date() format only but I cant convert to UTC time.

example 
var time = new Date(); <-- its work 
var time = new Date(timestamp * 1000).toUTCString(); <--- its error 

scope.model.setHours is not a function

**Comment by phng** [comment]
scope.model is expecting a Date() type. You might need to convert back to Date type from UTC string.
